# Download and install the specified version of WP if not already installed,
# ensure the configuration and permissions are correct, and link WP to make it
# "live" on the server.

- name: ensure wordpress mysql database exists
  mysql_db: name={{wp_db_name}} state=present

- name: check if specified wordpress version has already been downloaded
  stat: path={{wp_install_dir}}
  register: wp_dir

- include: install.yml
  when: "{{wp_force or not wp_dir.stat.exists}}"
  notify: restart php5-fpm

- name: ensure wordpress configuration is present
  template: src=wp-config dest={{wp_install_dir}}/wp-config.php
  notify: restart php5-fpm

- name: ensure permissions are set correctly
  file: state=directory recurse=yes dest={{wp_install_dir}} mode=777 owner={{wp_user}} group={{wp_group}}
  notify: restart php5-fpm

- name: ensure specified wordpress install is linked
  file: state=link src={{wp_install_dir}} path={{public_dir}} force=yes
  notify: restart php5-fpm

- name: link vagrant synced directory wp-content to make it live
  file:
    path: "{{public_dir}}/wp-content"
    src: "{{synced_folder}}/wp-content"
    state: link
    force: yes
    mode: 777
    owner: "{{wp_user}}"
    group: "{{wp_group}}"
