# This playbook saves the trouble of running each of the following playbooks
# individually, and is provided for convenience. After "vagrant up", this
# playbook will be run on the new Vagrant box.

- include: provision.yml
- include: configure.yml

# This playbook is not limited to being run on any particular host, but should
# only be auto-run in the development environment (Vagrant).
- include: db-restore.yml
  when: env == "development"
